# Generated by Django 2.0.2 on 2018-05-30 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diablo3_review', '0003_commentaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentaire',
            name='article',
        ),
        migrations.AddField(
            model_name='myarticle',
            name='comm',
            field=models.ManyToManyField(to='Diablo3_review.Commentaire'),
        ),
    ]
