# Generated by Django 2.0.2 on 2018-05-30 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diablo3_review', '0004_auto_20180530_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myarticle',
            name='comm',
            field=models.ManyToManyField(to='Diablo3_review.Commentaire', verbose_name='comm'),
        ),
    ]
